version: "3.9"

services:
  registry:
    restart: always
    image: registry:2
    ports:
      - "443:5000"
    volumes:
      - ./data:/var/lib/registry
      - ${LETSENCRYPT_CERTS_DIRECTORY}:/certs
      - ./auth:/auth
    environment:
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/fullchain.pem
      - REGISTRY_HTTP_TLS_KEY=/certs/privkey.pem
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
